// User
export const ERROR_RECEIVE_USER = 'ERROR_RECEIVE_USER';
export const REQUEST_USER = 'REQUEST_USER';
export const RECEIVE_USER = 'RECEIVE_USER';

export const ERROR_SIGN_IN = 'ERROR_SIGN_IN';
export const REQUEST_SIGN_IN = 'REQUEST_SIGN_IN';
export const SUCCESS_SIGN_IN = 'SUCCESS_SIGN_IN';

export const ERROR_SIGN_UP = 'ERROR_SIGN_UP';
export const REQUEST_SIGN_UP = 'REQUEST_SIGN_UP';
export const SUCCESS_SIGN_UP = 'SUCCESS_SIGN_UP';

export const REQUEST_SIGN_OUT = 'REQUEST_SIGN_OUT';


//SongsList
export const REQUEST_SONGS = 'REQUEST_SONGS';
export const RECEIVE_SONGS = 'RECEIVE_SONG';
export const ERROR_RECEIVE_SONGS = 'ERROR_RECEIVE_SONGS';

//Song
export const SET_MODE = 'SET_MODE';
export const REQUEST_GET_SONG = 'REQUEST_GET_SONG';
export const SUCCESS_GET_SONG = 'SUCCESS_GET_SONG';
export const ERROR_GET_SONG = 'ERROR_GET_SONG';

export const REQUEST_DELETE_SONG = 'REQUEST_DELETE_SONG';
export const SUCCESS_DELETE_SONG = 'SUCCESS_DELETE_SONG';
export const ERROR_DELETE_SONG = 'ERROR_DELETE_SONG';

export const REQUEST_CREATE_SONG = 'REQUEST_CREATE_SONG';
export const SUCCESS_CREATE_SONG = 'SUCCESS_CREATE_SONG';
export const ERROR_CREATE_SONG = 'ERROR_CREATE_SONG';

export const REQUEST_UPDATE_SONG = 'REQUEST_UPDATE_SONG';
export const SUCCESS_UPDATE_SONG = 'SUCCESS_UPDATE_SONG';
export const ERROR_UPDATE_SONG = 'ERROR_UPDATE_SONG';

//Playlists
export const REQUEST_PLAYLISTS = 'REQUEST_PLAYLISTS';
export const SUCCESS_PLAYLISTS = 'SUCCESS_PLAYLISTS';
export const ERROR_PLAYLISTS = 'ERROR_PLAYLISTS';

