export const MOCK_SONGS_RESPONSE = [
    {
        id: 1,
        name: 'The Last Train',
        artist: 'Zenith Core',
        year: 2020,
        playlistId: 5,
    },
    {
        id: 2,
        name: 'Night Drive',
        artist: 'Synth Wave',
        year: 2021,
        playlistId: 3,
    },
    {
        id: 3,
        name: 'Echoes',
        artist: 'Zenith Core',
        year: 2020,
        playlistId: 5,
    },
    {
        id: 4,
        name: 'Neon Lights',
        artist: 'Synth Wave',
        year: 2019,
        playlistId: 3,
    },
    {
        id: 5,
        name: 'Fading Stars',
        artist: 'Lunar Sky',
        year: 2022,
        playlistId: 1,
    },
    {
        id: 6,
        name: 'Midnight Pulse',
        artist: 'Zenith Core',
        year: 2021,
        playlistId: 5,
    },
    {
        id: 7,
        name: 'Cold Horizons',
        artist: 'Arctic Flow',
        year: 2018,
        playlistId: 2,
    },
    {
        id: 8,
        name: 'Digital Dreams',
        artist: 'Synth Wave',
        year: 2020,
        playlistId: 3,
    },
    {
        id: 9,
        name: 'Silent Motion',
        artist: 'Lunar Sky',
        year: 2019,
        playlistId: 1,
    },
    {
        id: 10,
        name: 'Afterglow',
        artist: 'Aurora Line',
        year: 2022,
        playlistId: 4,
    },
    {
        id: 11,
        name: 'Gravity',
        artist: 'Aurora Line',
        year: 2021,
        playlistId: 4,
    },
    {
        id: 12,
        name: 'Lost Signal',
        artist: 'Arctic Flow',
        year: 2020,
        playlistId: 2,
    },
    {
        id: 13,
        name: 'Crystal City',
        artist: 'Neon Atlas',
        year: 2019,
        playlistId: 6,
    },
    {
        id: 14,
        name: 'High Voltage',
        artist: 'Neon Atlas',
        year: 2021,
        playlistId: 6,
    },
    {
        id: 15,
        name: 'Endless Loop',
        artist: 'Zenith Core',
        year: 2022,
        playlistId: 5,
    },
    {
        id: 16,
        name: 'Shadows',
        artist: 'Lunar Sky',
        year: 2018,
        playlistId: 1,
    },
    {
        id: 17,
        name: 'Overdrive',
        artist: 'Synth Wave',
        year: 2022,
        playlistId: 3,
    },
    {
        id: 18,
        name: 'Northern Lights',
        artist: 'Arctic Flow',
        year: 2021,
        playlistId: 2,
    },
    {
        id: 19,
        name: 'Skyline',
        artist: 'Aurora Line',
        year: 2019,
        playlistId: 4,
    },
    {
        id: 20,
        name: 'Final Echo',
        artist: 'Neon Atlas',
        year: 2022,
        playlistId: 6,
    },
];
